version: '3.7'

services:
  api:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 80:8000
    restart: always
    networks: 
      - engine 

# I have created a network just in case we want to add everything 
  
  
networks:
    engine:
      external:
        name: engine
