global:
  checkNewVersion: false
  sendAnonymousUsage: false
serversTransport:
  insecureSkipVerify: true
  maxIdleConnsPerHost: 10
  forwardingTimeouts:
    dialTimeout: 5s
    responseHeaderTimeout: 10s
    idleConnTimeout: 10s
defaultEntryPoints: http
entryPoints:
  http:
    address: :80
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 10s
        graceTimeOut: 30s
      respondingTimeouts:
        readTimeout: 10s
        writeTimeout: 10s
        idleTimeout: 10s
  https:
    address: :443
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 10s
        graceTimeOut: 30s
      respondingTimeouts:
        readTimeout: 10s
        writeTimeout: 10s
        idleTimeout: 10s
providers:
  docker:
    watch: true
    swarmMode: false
    network: object_cut
api:
  insecure: true
  dashboard: true
  debug: false
ping:
  entryPoint: http
accessLog:
  format: json
  bufferingSize: 100
  fields:
    defaultMode: drop
    names:
      ClientAddr: keep
      RequestAddr: keep
      RequestPath: keep
    headers:
      defaultMode: drop
