# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Create .env file
      run: echo "SECRET_ACCESS=${{ secrets.SECRET_ACCESS }}" >> .env
    - name: Setup Google Cloud Storage credentials
      run: echo "${{ secrets.GOOGLE_CLOUD_STORAGE_ACCESS }}" >> ./multiplexer/keys/google_cloud_storage_access.json
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r multiplexer/requirements.lock
        pip install -r inference/requirements.lock
    - name: Lint with flake8
      working-directory: ${{env.api-directory}}
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Deploy stack
      run: docker-compose up -d --build --scale multiplexer=1 --scale inference=3
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '5s'
    - name: Check running containers
      run: docker ps
    - name: Test with unittest
      working-directory: ./multiplexer
      run: export $(cat ../.env | xargs) && python3 -m unittest discover -v
